export const mockItems = [
  {
    id: 1,
    name: "Apple",
    price: 120,
    uom: "kg",
    category: "Fruits",
  },
  {
    id: 2,
    name: "Banana",
    price: 50,
    uom: "dozen",
    category: "Fruits",
  },
  {
    id: 3,
    name: "Tomato",
    price: 35,
    uom: "kg",
    category: "Vegetables",
  },
  {
    id: 4,
    name: "Potato",
    price: 25,
    uom: "kg",
    category: "Vegetables",
  },
  {
    id: 5,
    name: "Onion",
    price: 30,
    uom: "kg",
    category: "Vegetables",
  },
  {
    id: 6,
    name: "Milk",
    price: 60,
    uom: "litre",
    category: "Dairy",
  },
  {
    id: 7,
    name: "Wheat Flour",
    price: 40,
    uom: "kg",
    category: "Grocery",
  },
  {
    id: 8,
    name: "Rice",
    price: 55,
    uom: "kg",
    category: "Grocery",
  },
  {
    id: 9,
    name: "Eggs",
    price: 70,
    uom: "dozen",
    category: "Poultry",
  },
  {
    id: 10,
    name: "Sugar",
    price: 45,
    uom: "kg",
    category: "Grocery",
  },
  {
    id: 11,
    name: "Cheese",
    price: 250,
    uom: "kg",
    category: "Dairy",
  },
  {
    id: 12,
    name: "Cucumber",
    price: 20,
    uom: "kg",
    category: "Vegetables",
  },
  {
    id: 13,
    name: "Orange",
    price: 90,
    uom: "kg",
    category: "Fruits",
  },
  {
    id: 14,
    name: "Mango",
    price: 150,
    uom: "kg",
    category: "Fruits",
  },
  {
    id: 15,
    name: "Green Peas",
    price: 60,
    uom: "kg",
    category: "Vegetables",
  },
  {
    id: 16,
    name: "Butter",
    price: 200,
    uom: "kg",
    category: "Dairy",
  },
  {
    id: 17,
    name: "Chicken",
    price: 180,
    uom: "kg",
    category: "Poultry",
  },
  {
    id: 18,
    name: "Paneer",
    price: 300,
    uom: "kg",
    category: "Dairy",
  },
  {
    id: 19,
    name: "Salt",
    price: 20,
    uom: "kg",
    category: "Grocery",
  },
  {
    id: 20,
    name: "Bread",
    price: 40,
    uom: "loaf",
    category: "Bakery",
  },
];



export const mockUsers = [
  {
    id: 1,
    usercode: "USR001",
    name: "Amit Sharma",
    customer: "Reliance Retail",
    categories: ["Admin", "Inventory"],
  },
  {
    id: 2,
    usercode: "USR002",
    name: "Sara Khan",
    customer: "BigBasket",
    categories: ["Sales", "Fruits"],
  },
  {
    id: 3,
    usercode: "USR003",
    name: "Ravi Kumar",
    customer: "Spencer's",
    categories: ["Procurement", "Vegetables"],
  },
  {
    id: 4,
    usercode: "USR004",
    name: "Meena Iyer",
    customer: "More Supermarket",
    categories: ["Reports", "Billing"],
  },
  {
    id: 5,
    usercode: "USR005",
    name: "John D'Souza",
    customer: "Nature's Basket",
    categories: ["Admin"],
  },
]


export const mockCategories = [
  {
    id: "cat001",
    name: "Electronics",
    description: "Devices, gadgets, and accessories.",
    image: "https://via.placeholder.com/100x100?text=Electronics",
    createdAt: "2024-12-01",
    updatedAt: "2025-01-15",
    status: "active",
  },
  {
    id: "cat002",
    name: "Fashion",
    description: "Clothing, footwear, and accessories.",
    image: "https://via.placeholder.com/100x100?text=Fashion",
    createdAt: "2025-01-10",
    updatedAt: "2025-02-12",
    status: "active",
  },
  {
    id: "cat003",
    name: "Books",
    description: "Printed and digital books across genres.",
    image: "https://via.placeholder.com/100x100?text=Books",
    createdAt: "2024-11-20",
    updatedAt: "2025-01-05",
    status: "inactive",
  },
  {
    id: "cat004",
    name: "Home & Kitchen",
    description: "Appliances, furniture, and decor.",
    image: "https://via.placeholder.com/100x100?text=Home+%26+Kitchen",
    createdAt: "2025-03-01",
    updatedAt: "2025-03-18",
    status: "active",
  },
  {
    id: "cat005",
    name: "Toys & Games",
    description: "Toys for kids and family games.",
    image: "https://via.placeholder.com/100x100?text=Toys+%26+Games",
    createdAt: "2025-04-15",
    updatedAt: "2025-04-20",
    status: "active",
  },
  {
    id: "cat006",
    name: "Health & Beauty",
    description: "Skincare, wellness, and beauty products.",
    image: "https://via.placeholder.com/100x100?text=Health+%26+Beauty",
    createdAt: "2025-02-25",
    updatedAt: "2025-03-10",
    status: "active",
  },
  {
    id: "cat007",
    name: "Sports & Outdoors",
    description: "Fitness equipment and outdoor gear.",
    image: "https://via.placeholder.com/100x100?text=Sports+%26+Outdoors",
    createdAt: "2024-10-05",
    updatedAt: "2025-01-22",
    status: "inactive",
  },
];


export const mockVehicles = [
  {
    id: "veh001",
    name: "Tata Ace",
    number: "TN 01 AB 1234",
    image: "https://via.placeholder.com/100x60?text=Tata+Ace",
    driverName: "Ravi Kumar",
    driverContact: "+91 9876543210",
    assignedCustomers: ["Arun Babu", "Divya Ramesh"],
    assignedCategory: "Logistics",
  },
  {
    id: "veh002",
    name: "Mahindra Bolero Pickup",
    number: "TN 22 CD 5678",
    image: "https://via.placeholder.com/100x60?text=Bolero+Pickup",
    driverName: "Suresh M",
    driverContact: "+91 9845098450",
    assignedCustomers: ["Mohammed Faiz"],
    assignedCategory: "Delivery",
  },
  {
    id: "veh003",
    name: "Ashok Leyland Dost",
    number: "TN 14 EF 9101",
    image: "https://via.placeholder.com/100x60?text=Dost",
    driverName: "Vignesh K",
    driverContact: "+91 9361547683",
    assignedCustomers: ["Lakshmi Priya", "Karthik Ram", "Sonal Mehta"],
    assignedCategory: "Transport",
  },
  {
    id: "veh004",
    name: "Force Traveller",
    number: "TN 11 GH 2233",
    image: "https://via.placeholder.com/100x60?text=Traveller",
    driverName: "Anand Raj",
    driverContact: "+91 9798797987",
    assignedCustomers: [],
    assignedCategory: "Passenger",
  },
  {
    id: "veh005",
    name: "Eicher Pro 1049",
    number: "TN 18 IJ 3344",
    image: "https://via.placeholder.com/100x60?text=Eicher+Pro",
    driverName: "Muthu V",
    driverContact: "+91 9884411220",
    assignedCustomers: ["Vinod Patil"],
    assignedCategory: "Heavy Load",
  },
  {
    id: "veh006",
    name: "Piaggio Ape",
    number: "TN 05 KL 4455",
    image: "https://via.placeholder.com/100x60?text=Ape",
    driverName: "Karthik S",
    driverContact: "+91 9090909090",
    assignedCustomers: ["Deepak Sharma", "Neha Sinha"],
    assignedCategory: "Local Delivery",
  },
  {
    id: "veh007",
    name: "Maruti Omni",
    number: "TN 08 MN 5566",
    image: "https://via.placeholder.com/100x60?text=Omni",
    driverName: "Ramesh B",
    driverContact: "+91 9888801122",
    assignedCustomers: [],
    assignedCategory: "Private Transport",
  },
  {
    id: "veh008",
    name: "Isuzu D-Max",
    number: "TN 07 OP 6677",
    image: "https://via.placeholder.com/100x60?text=D-Max",
    driverName: "Ganesh D",
    driverContact: "+91 9555588888",
    assignedCustomers: ["Praveen Kumar", "Anjali Verma", "Ritu Jain"],
    assignedCategory: "Industrial",
  },
  {
    id: "veh009",
    name: "Toyota Innova",
    number: "TN 09 QR 7788",
    image: "https://via.placeholder.com/100x60?text=Innova",
    driverName: "Rajesh P",
    driverContact: "+91 9988776655",
    assignedCustomers: ["Rajiv Menon"],
    assignedCategory: "Corporate Travel",
  },
  {
    id: "veh010",
    name: "Ashok Leyland Partner",
    number: "TN 10 ST 8899",
    image: "https://via.placeholder.com/100x60?text=Partner",
    driverName: "Sathish K",
    driverContact: "+91 9000001111",
    assignedCustomers: ["Sneha D", "Manoj Pillai"],
    assignedCategory: "Construction",
  },
];

export const mockUOM = [
  { id: "uom001", name: "Piece", code: "PCS" },
  { id: "uom002", name: "Kilogram", code: "KG" },
  { id: "uom003", name: "Gram", code: "GM" },
  { id: "uom004", name: "Liter", code: "LTR" },
  { id: "uom005", name: "Meter", code: "MTR" },
  { id: "uom006", name: "Box", code: "BOX" },
  { id: "uom007", name: "Dozen", code: "DOZ" },
  { id: "uom008", name: "Milliliter", code: "ML" },
  { id: "uom009", name: "Centimeter", code: "CM" },
  { id: "uom010", name: "Pack", code: "PK" },
];


export const mockCustomers = [
  { id: "cust001", name: "Arun Babu" },
  { id: "cust002", name: "Divya Ramesh" },
  { id: "cust003", name: "Mohammed Faiz" },
  { id: "cust004", name: "Lakshmi Priya" },
  { id: "cust005", name: "Karthik Ram" },
  { id: "cust006", name: "Sonal Mehta" },
  { id: "cust007", name: "Vinod Patil" },
  { id: "cust008", name: "Deepak Sharma" },
  { id: "cust009", name: "Neha Sinha" },
  { id: "cust010", name: "Praveen Kumar" },
  { id: "cust011", name: "Anjali Verma" },
  { id: "cust012", name: "Ritu Jain" },
  { id: "cust013", name: "Rajiv Menon" },
  { id: "cust014", name: "Sneha D" },
  { id: "cust015", name: "Manoj Pillai" },
];
